# Generated by Django 4.2.6 on 2023-12-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
