# Generated by Django 4.2.6 on 2023-12-19 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_order_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='disc',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='discount',
            old_name='disc',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='disc',
            new_name='desc',
        ),
        migrations.RemoveField(
            model_name='parentcategory',
            name='disc',
        ),
        migrations.AddField(
            model_name='category',
            name='discount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parentcategory',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parentcategory',
            name='discount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
