# Generated by Django 5.0 on 2023-12-11 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
