# Generated by Django 4.2.6 on 2023-12-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_cuser_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuser',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='cuser',
            name='image',
            field=models.ImageField(null=True, upload_to='profile'),
        ),
    ]
